[2023-11-08T13:13:33.159+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag.create_cases_deaths_query_operator manual__2023-11-08T13:11:55.720846+00:00 [queued]>
[2023-11-08T13:13:33.356+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag.create_cases_deaths_query_operator manual__2023-11-08T13:11:55.720846+00:00 [queued]>
[2023-11-08T13:13:33.373+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-08T13:13:33.698+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_cases_deaths_query_operator> on 2023-11-08 13:11:55.720846+00:00
[2023-11-08T13:13:33.799+0000] {standard_task_runner.py:57} INFO - Started process 4646 to run task
[2023-11-08T13:13:33.911+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag', 'create_cases_deaths_query_operator', 'manual__2023-11-08T13:11:55.720846+00:00', '--job-id', '470', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmp7w6o5f8h']
[2023-11-08T13:13:33.922+0000] {standard_task_runner.py:85} INFO - Job 470: Subtask create_cases_deaths_query_operator
[2023-11-08T13:13:34.209+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag.create_cases_deaths_query_operator manual__2023-11-08T13:11:55.720846+00:00 [running]> on host 172.21.0.9
[2023-11-08T13:13:34.480+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-11-08T13:13:34.715+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag' AIRFLOW_CTX_TASK_ID='create_cases_deaths_query_operator' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T13:11:55.720846+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T13:11:55.720846+00:00'
[2023-11-08T13:13:34.874+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dag_postgres.py", line 52, in _create_cases_deaths_query
    df = pd.read_csv('/opt/airflow/dags/cases_deaths.csv')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2029, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 127 fields in line 24, saw 169

[2023-11-08T13:13:35.001+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_dag, task_id=create_cases_deaths_query_operator, execution_date=20231108T131155, start_date=20231108T131333, end_date=20231108T131335
[2023-11-08T13:13:35.116+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 470 for task create_cases_deaths_query_operator (Error tokenizing data. C error: Expected 127 fields in line 24, saw 169
; 4646)
[2023-11-08T13:13:35.204+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T13:13:35.344+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
