[2023-11-14T07:59:27.716+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres.wrangle_government_measures manual__2023-11-13T17:01:03.783643+00:00 [queued]>
[2023-11-14T07:59:27.767+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres.wrangle_government_measures manual__2023-11-13T17:01:03.783643+00:00 [queued]>
[2023-11-14T07:59:27.767+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-11-14T07:59:27.811+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): wrangle_government_measures> on 2023-11-13 17:01:03.783643+00:00
[2023-11-14T07:59:27.820+0000] {standard_task_runner.py:57} INFO - Started process 154 to run task
[2023-11-14T07:59:27.826+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres', 'wrangle_government_measures', 'manual__2023-11-13T17:01:03.783643+00:00', '--job-id', '866', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmpscbtm1p1']
[2023-11-14T07:59:27.848+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: covid_data_dag_postgres.wrangle_government_measures manual__2023-11-13T17:01:03.783643+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-11-14T07:59:27.855+0000] {standard_task_runner.py:85} INFO - Job 866: Subtask wrangle_government_measures
[2023-11-14T07:59:27.857+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: covid_data_dag_postgres.wrangle_government_measures manual__2023-11-13T17:01:03.783643+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-11-14T07:59:27.860+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-11-14T07:59:28.236+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag_postgres.wrangle_government_measures manual__2023-11-13T17:01:03.783643+00:00 [running]> on host 172.21.0.4
[2023-11-14T07:59:28.450+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag_postgres' AIRFLOW_CTX_TASK_ID='wrangle_government_measures' AIRFLOW_CTX_EXECUTION_DATE='2023-11-13T17:01:03.783643+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-13T17:01:03.783643+00:00'
[2023-11-14T07:59:44.149+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-14T07:59:44.167+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=covid_data_dag_postgres, task_id=wrangle_government_measures, execution_date=20231113T170103, start_date=20231114T075927, end_date=20231114T075944
[2023-11-14T07:59:44.253+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-14T07:59:44.675+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
